# Uncomment the next line to define a global platform for your project
platform :ios, "12.2"
source 'https://github.com/CocoaPods/Specs.git'

target 'ZFWaterMark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZFWaterMark
  pod 'OpenCV'
end
